DefaultContentLanguage = "en"
"Languages.en.params.aboutSm.description" = ""
"Languages.en.params.aboutSm.title" = ""
"Languages.en.params.hero.btnText" = ""
"Languages.en.params.hero.btnURL" = ""
"Languages.en.params.hero.description" = ""
"Languages.en.params.hero.heading" = ""
"Languages.en.params.hero.photo" = ""
baseURL = "https://www.finerimmigration.com.au/"
defaultContentLanguageInSubdir = false
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
main_photo = ""
pygmentsCodeFences = true
theme = "navigator"
title = "Finer Immigration"
[Languages.en]
dateFormat = "January 2, 2006"
footerAboutTitle = "ENGLISH About"
footerDescription = "ENGLISH Integer posuere erat a ante venenati dapibus posuere velit aliquet. Fusce dapibus, tellus cursus commodo, tortor mauris sed posuere."
footerQuicklinkTitle = "ENGLISH Quicklinks"
footerServiceTitle = "ENGLISH Service"
footerSubscribeTitle = "ENGLISH Subscribe"
home = "Home"
languageCode = "en-us"
logo = "images/logo.png"
menufixed = false
title = "ENGLISH Example site multi-language"
weight = 2
[Languages.en.params.aboutSm]
description = "Employer Sponsorship is not one-size fits-all, it is important that you find the right visa for your employee to suit your company structure "
enable = true
title = "Employer Sponsored Visas"
[Languages.en.params.blog]
enable = true
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
title = "ENGLISH Blog."
topTitle = "OUR UNTOLD STORY"
[Languages.en.params.contact]
address = "14/05, Stockhome <br> Victori Palace , United States"
dribbble = "https://dribbble.com/"
enable = true
facebook = "https://www.facebook.com/"
fax = "+61 3827 3590"
instagram = "https://www.instagram.com/"
linkedin = "https://www.linkedin.com/"
mapLatitude = 51.507351
mapLongitude = -0.127758
mapMarker = "images/marker.png"
phone = "(03) 9283 2617"
subtitle = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illum reiciendis quasi itaque, obcaecati atque sit!"
title = "Contact Us."
topTitle = "DROP US A NOTE"
twitter = "https://twitter.com/"
[Languages.en.params.cta]
bg = "images/call-to-action/call-to-action-bg-2.jpg"
btnText = "Contact Us"
enable = true
subtitle = "Proin gravida nibh vel velit auctor aliquet. Aenean sollicudin bibendum auctor, <br> nisi elit consequat ipsum, nesagittis sem nid elit. Duis sed odio sitain elit."
title = "ENGLISH Let's Create Something Together"
[Languages.en.params.hero]
btnText = "Know More "
btnURL = "https://themefisher.com/"
button = true
description = "Australian Immigration specialists. We are specialising on Australian Employer Sponsored Visas,Administrative Appeals Tribunal ( AAT), and Federal Court of Australia (FCOA). Our experienced lawyers/migration specialists aim to help your valued employees Live & Work in Australia."
enable = true
heading = "FINER IMMIGRATION We love to assist your business grow"
photo = "/images/slider/video-player-thumb.jpg"
videoThumb = "images/slider/video-player-thumb.jpg"
videoURL = "https://www.youtube.com/embed/g3-VxLQO7do"
[[menu.nav]]
name = "contact"
url = "contact"
weight = 5
[[menu.quicklink]]
name = "badges"
url = "about"
weight = 4
[[menu.quicklink]]
name = "faqs"
url = "about"
weight = 3
[[menu.quicklink]]
name = "about"
url = "about"
weight = 2
[[menu.quicklink]]
name = "partners"
url = "about"
weight = 1
[[menu.service]]
name = "webdevelopment"
url = "service"
weight = 3
[[menu.service]]
name = "webdesign"
url = "service"
weight = 2
[[menu.service]]
name = "graphicdesign"
url = "service"
weight = 1
[params]
logo = "images/logo.png"
