---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: date/en/feature.yml
  label: Services
- type: document
  path: config.toml
  label: Config
- type: directory
  path: data/en
  label: data
  create: all
  match: "**/*"
- type: directory
  path: content
  label: Pages
  create: all
  match: "*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
