---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: Top Section
- type: document
  path: data/en/feature.yml
  label: Services
- type: document
  path: data/en/about.yml
  label: Features
  match: "**/*"
- type: document
  path: data/en/workingprocess.yml
  label: Working Process
- type: directory
  path: data/en
  label: All Config
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
