---
new_page_extension: md
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: document
  path: config.toml
  label: 'Homepage: Top'
- type: document
  path: data/en/workingprocess.yml
  label: 'Homepage: Process'
- type: document
  path: data/en/feature.yml
  label: 'Homepage: Services'
- type: document
  path: data/en/about.yml
  label: 'Homepage: Features'
- type: document
  path: data/en/portfolio.yml
  label: 'Homepage: Portfolio'
- type: document
  path: data/en/philosophy.yml
  label: 'Outcomes: Middle'
- type: document
  path: data/en/service.yml
  label: 'Services: Top'
- type: document
  path: data/en/clients.yml
  label: 'Services: Middle'
- type: document
  path: data/en/testimonial.yml
  label: 'Services: Bottom'
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  exclude: _index.en.md
- type: directory
  path: data/en
  label: All Config
  create: all
  match: "**/*"
upload_dir: static/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
version: '0.52'
