---
label: Finer Immigration1
hide_body: false
is_partial: false
fields:
- name: Languages.en.params.hero
  label: Heading
  type: field_group_list
  fields:
  - name: heading
    label: Heading
    type: text
    hidden: false
    default: ''
  - name: description
    label: Heading
    type: text
    hidden: false
    default: ''
  - name: btnText
    label: Button Text
    type: text
    hidden: false
    default: ''
  - name: btnURL
    label: Button URL
    type: text
    hidden: false
    default: ''
  - name: Languages.en.params.aboutSm
    label: About
    type: field_group_list
    fields:
    - name: title
      label: Title
      type: text
      hidden: false
      default: ''
    - name: description
      label: Description
      type: textarea
      hidden: false
      default: ''
pages:
- config.toml
