---
label: Top Section
hide_body: false
is_partial: false
fields:
- type: file
  label: photo
  name: hp_photo
  description: Homepage main photo
- name: Languages.en.params.hero.heading
  label: Heading
  type: text
  hidden: false
  default: ''
- name: Languages.en.params.hero.description
  label: Heading
  type: text
  hidden: false
  default: ''
- name: Languages.en.params.hero.btnText
  label: Button Text
  type: text
  hidden: false
  default: ''
- name: Languages.en.params.hero.btnURL
  label: Button URL
  type: text
  hidden: false
  default: ''
pages:
- config.toml
